//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class staff
    {
        public int id { get; set; }

        [DisplayName("Code")]
        public int code { get; set; }

        [DisplayName("First Name")]
        public string firstname { get; set; }

        [DisplayName("Last Name")]
        public string lastname { get; set; }

        [DisplayName("Father Name")]
        public string fathername { get; set; }

        [DisplayName("DOJ")]
        public System.DateTime doj { get; set; }

        [DisplayName("Salary")]
        public string salary { get; set; }

        [DisplayName("Address")]
        public string address { get; set; }

        [DisplayName("Aadhar No.")]
        public string aadharno { get; set; }

        [DisplayName("Account No.")]
        public string accountno { get; set; }
    }
}
